# Generated by Django 6.0 on 2026-01-10 11:16

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internetBanking', '0002_ibtransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='ibtransactions',
            name='receiver_account',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ibtransactions',
            name='remark',
            field=models.CharField(default=datetime.datetime(2026, 1, 10, 11, 15, 57, 742476, tzinfo=datetime.timezone.utc), max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ibtransactions',
            name='sender_account',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ibtransactions',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
