# Generated by Django 6.0 on 2026-01-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internetBanking', '0003_ibtransactions_receiver_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibtransactions',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
