# Generated by Django 6.0 on 2025-12-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=12)),
                ('email_id', models.EmailField(max_length=30)),
                ('mobile', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=70)),
                ('pincode', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('aadhar_no', models.CharField(max_length=20)),
                ('ac_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
