# Generated by Django 6.0 on 2026-01-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_information_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_active',
        ),
        migrations.AddField(
            model_name='account',
            name='internet_banking_is_active',
            field=models.CharField(choices=[('Y', 'y'), ('N', 'n')], default='Y', max_length=10),
        ),
    ]
